version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media_data:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  daphne:
    build: .
    command: daphne -b 0.0.0.0 -p 8005 demo_project.asgi:application
    volumes:
      - .:/app
    ports:
      - "8005:8005"
    depends_on:
      - web
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A demo_project worker -l info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis

  celery-beat:
    build: .
    command: celery -A demo_project beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - web
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: demodb
      POSTGRES_USER: demouser
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  media_data:
