# Generated by Django 5.2.5 on 2025-09-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_taskattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattachment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='task_images/'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='task_attachments/'),
        ),
    ]
