# Generated by Django 5.2.5 on 2025-09-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_taskattachment_image_alter_taskattachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
